import tkinter as tk
from tkinter import ttk, messagebox, scrolledtext
import math

# ============================================================
# Функция генерации G-кода (без изменений)
# ============================================================
def generate_gcode(params):
    D_freza = params['D_freza']
    X_start = params['X_start']
    X_finish = params['X_finish']
    Z_start = params['Z_start']
    Z_finish = params['Z_finish']
    shag_X = params['shag_X']
    F_cher = params['F_cher']
    radius_skrug = params['radius_skrug']
    pripusk = params['pripusk']
    napravlenie = params['napravlenie']
    F_chist = params['F_chist']
    shag_Z = params['shag_Z']

    if napravlenie == 0 or napravlenie > 1 or napravlenie < -1:
        napravlenie = -1
    if F_chist == 0:
        F_chist = F_cher
    if shag_Z == 0:
        shag_Z = 1.0

    shag_tek = shag_X
    D_opisan = X_start + (D_freza / 4.0) * 1.1547 + shag_tek * 2.0
    D_chet = D_opisan / 4.0
    R_sopr = radius_skrug + D_freza / 2.0
    D_s_pripusk = X_finish + D_freza + pripusk
    flag_ostry = 0 if radius_skrug == 0 else 1
    if radius_skrug == 0:
        R_sopr = 0.0
    sign = napravlenie

    gcode_lines = []
    gcode_lines.append("%O0209")
    gcode_lines.append("(6-gr AX po osi C - generated by CNC GUI)")
    gcode_lines.append("(NL2500)")
    gcode_lines.append("G0 G30 U0 V0")
    gcode_lines.append("G30 W0")
    gcode_lines.append("T0909")
    gcode_lines.append("M45 G99 G40 G80 G54")
    gcode_lines.append("G28 H0")
    gcode_lines.append("G97 S2000 M13 P2")
    gcode_lines.append("M67")
    gcode_lines.append("G17")
    gcode_lines.append("G0 Z10.")
    gcode_lines.append(f"G0 X{D_opisan + D_freza + 5:.3f}")
    gcode_lines.append("G0 Z2.")
    gcode_lines.append("M08")
    gcode_lines.append("G112")
    gcode_lines.append(f"G1 C{-sign * D_opisan / 2:.3f} F0.5")

    def generate_pass(D_tek, C_tek, i, F_feed):
        lines = []
        if flag_ostry == 1:
            X_start_move = D_tek + shag_tek * 2.0
            lines.append(f"G1 X{X_start_move:.3f} C{sign * C_tek:.3f} F0.5")
            lines.append(f"G1 X{D_tek:.3f} C{sign * C_tek:.3f} F0.5")
        else:
            lines.append(f"G1 X{D_tek:.3f} C{sign * C_tek:.3f} F0.5")
        lines.append(f"G1 C{-sign * C_tek:.3f} R{R_sopr:.3f} F{F_feed:.3f}")
        C2 = -sign * (D_tek / 2.0 * 1.1547)
        lines.append(f"G1 X0.000 C{C2:.3f} R{R_sopr:.3f} F{F_feed:.3f}")
        lines.append(f"G1 X{-D_tek:.3f} C{-sign * C_tek:.3f} R{R_sopr:.3f} F{F_feed:.3f}")
        lines.append(f"G1 C{sign * C_tek:.3f} R{R_sopr:.3f} F{F_feed:.3f}")
        C5 = sign * (D_tek / 2.0 * 1.1547)
        lines.append(f"G1 X0.000 C{C5:.3f} R{R_sopr:.3f} F{F_feed:.3f}")
        lines.append(f"G1 X{D_tek:.3f} C{sign * C_tek:.3f} R{R_sopr:.3f} F{F_feed:.3f}")
        if flag_ostry == 1:
            lines.append(f"G1 X{D_tek + 0.2:.3f} C0.000 F{F_feed:.3f}")
        return lines

    z_positions = []
    z_current = Z_start
    count_z = 0
    while z_current > Z_finish:
        z_current = Z_start - shag_Z * (count_z + 1)
        if z_current < Z_finish:
            z_current = Z_finish
        z_positions.append(z_current)
        count_z += 1
        if z_current == Z_finish:
            break

    for z in z_positions:
        gcode_lines.append(f"G0 Z{z:.3f} F0.5")
        i = 1
        while True:
            D_tek = D_opisan - i * shag_tek + (D_freza / 2.0) * 1.1547
            C_tek = D_chet * 1.1547 - (0.577 * shag_tek / 2.0 * i) + (D_freza / 2.0 * 1.1547 / 4.0 * 1.15)
            if D_tek <= D_s_pripusk:
                D_tek = D_s_pripusk
                C_tek = D_s_pripusk / 4.0 * 1.1547
                pass_lines = generate_pass(D_tek, C_tek, i, F_cher)
                gcode_lines.extend(pass_lines)
                D_chist = X_finish + D_freza
                C_chist = D_chist / 4.0 * 1.1547
                pass_lines_chist = generate_pass(D_chist, C_chist, i, F_chist)
                gcode_lines.extend(pass_lines_chist)
                break
            else:
                pass_lines = generate_pass(D_tek, C_tek, i, F_cher)
                gcode_lines.extend(pass_lines)
                i += 1

    gcode_lines.append("G113")
    gcode_lines.append("G0 Z10.")
    gcode_lines.append("M5")
    gcode_lines.append("G18")
    gcode_lines.append("M46 G99")
    gcode_lines.append("M67")
    gcode_lines.append("G30 U0 M9")
    gcode_lines.append("G30 W0")
    gcode_lines.append("M30")
    gcode_lines.append("%")
    return "\n".join(gcode_lines)

# ============================================================
# Класс GUI – кнопки в одной строке
# ============================================================
class CNCApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Генератор G-кода для шестигранника (Fanuc)")
        self.root.geometry("700x850")
        self.root.resizable(True, True)

        main_frame = ttk.Frame(root, padding="10")
        main_frame.pack(fill=tk.BOTH, expand=True)

        ttk.Label(main_frame, text="Введите параметры обработки", font=("Arial", 14, "bold")).grid(row=0, column=0, columnspan=4, pady=10)

        params_info = [
            ("Диаметр фрезы (мм)", "D_freza", 14.0, "#110"),
            ("Начальный X (мм)", "X_start", 18.0, "#122"),
            ("Конечный X (мм)", "X_finish", 11.8, "#112"),
            ("Начальный Z (мм)", "Z_start", 1.0, "#124"),
            ("Конечный Z (мм)", "Z_finish", -10.0, "#118"),
            ("Шаг по X (мм)", "shag_X", 1.25, "#133"),
            ("Подача черновая (мм/об)", "F_cher", 0.2, "#136"),
            ("Радиус скругления (мм)", "radius_skrug", 0.5, "#137"),
            ("Припуск (мм)", "pripusk", 0.1, "#139"),
            ("Направление фрезы (1 или -1)", "napravlenie", -1.0, "#121"),
            ("Подача чистовая (0=как черновая)", "F_chist", 0.0, "#142"),
            ("Шаг по Z (0=авто 1мм)", "shag_Z", 0.0, "#123"),
        ]

        self.entries = {}
        row = 1
        for label, var, default, comment in params_info:
            ttk.Label(main_frame, text=label, font=("Arial", 10)).grid(row=row, column=0, sticky="w", pady=4)
            entry = ttk.Entry(main_frame, width=15)
            entry.insert(0, str(default))
            entry.grid(row=row, column=1, padx=5, pady=4)
            ttk.Label(main_frame, text=comment, font=("Arial", 8), foreground="gray").grid(row=row, column=2, sticky="w", padx=5)
            self.entries[var] = entry
            row += 1

        # ---- РЯД КНОПОК (Генерировать, Выделить всё, Копировать) ----
        btn_frame = ttk.Frame(main_frame)
        btn_frame.grid(row=row, column=0, columnspan=4, pady=15)

        btn_generate = ttk.Button(btn_frame, text="Сгенерировать G-код", command=self.generate)
        btn_generate.pack(side=tk.LEFT, padx=5)

        btn_select = ttk.Button(btn_frame, text="Выделить всё", command=self.select_all)
        btn_select.pack(side=tk.LEFT, padx=5)

        btn_copy = ttk.Button(btn_frame, text="Копировать код", command=self.copy_code)
        btn_copy.pack(side=tk.LEFT, padx=5)

        # Поле вывода
        self.output_text = scrolledtext.ScrolledText(main_frame, height=25, width=80, font=("Courier New", 10))
        self.output_text.grid(row=row+1, column=0, columnspan=4, pady=10)

        # Кнопка сохранения (оставим снизу)
        btn_save = ttk.Button(main_frame, text="Сохранить в файл (generated_6gr.nc)", command=self.save_file)
        btn_save.grid(row=row+2, column=0, columnspan=4, pady=5)

    def get_params(self):
        params = {}
        for var, entry in self.entries.items():
            try:
                val = float(entry.get().replace(',', '.'))
            except ValueError:
                messagebox.showerror("Ошибка", f"Поле '{var}' должно быть числом.")
                raise
            params[var] = val
        return params

    def generate(self):
        try:
            params = self.get_params()
            gcode = generate_gcode(params)
            self.output_text.delete(1.0, tk.END)
            self.output_text.insert(tk.END, gcode)
        except Exception as e:
            messagebox.showerror("Ошибка генерации", str(e))

    def select_all(self):
        self.output_text.tag_add("sel", "1.0", "end")
        self.output_text.mark_set("insert", "1.0")
        self.output_text.see("insert")
        self.output_text.focus_set()

    def copy_code(self):
        gcode = self.output_text.get(1.0, tk.END).strip()
        if not gcode:
            messagebox.showwarning("Предупреждение", "Нет кода для копирования.")
            return
        self.root.clipboard_clear()
        self.root.clipboard_append(gcode)
        self.root.update()
        messagebox.showinfo("Скопировано", "Код скопирован в буфер обмена.")

    def save_file(self):
        try:
            gcode = self.output_text.get(1.0, tk.END).strip()
            if not gcode:
                messagebox.showwarning("Предупреждение", "Сначала сгенерируйте G-код.")
                return
            filename = "generated_6gr.nc"
            with open(filename, "w", encoding="utf-8") as f:
                f.write(gcode)
            messagebox.showinfo("Сохранено", f"Файл '{filename}' сохранён в папке с программой.")
        except Exception as e:
            messagebox.showerror("Ошибка сохранения", str(e))

# ============================================================
if __name__ == "__main__":
    root = tk.Tk()
    app = CNCApp(root)
    root.mainloop()
